### ISSUE TITLE
PicSur not available 

### ISSUE THREAD

**Issue by fruizaviles** [CaramelFur/Picsur#37]
I wanted to redeploy a clean install in my Synology DS720+ using Docker Compose in Portainer, as I have always done, and get an error, see pic:

![IMG_20230223_113106](https://user-images.githubusercontent.com/26512079/220890803-3a87f8aa-d42a-45ee-a757-a3215eb04a41.jpg)

Cheers

**Comment by CaramelFur** [comment]
Ah apologies, I forgot to update the readme, sadly docker containers don't redirect upon a github name change.
The new url should be in the readme, but here it is aswell: `ghcr.io/caramelfur/picsur:latest`, so use that as the container image. I hope this helps.
