### ISSUE TITLE
Can't pull image

### ISSUE THREAD

**Issue by Caalek** [CaramelFur/Picsur#41]
While pulling ghcr.io/CaramelFur/Picsur it throws an error:

`
error pulling image configuration: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a8704392d6914a8cf964e134bd151d70c891a987e518bb4f97ef98b216480104?se=2023-03-24T20%3A55%3A00Z&sig=XHjJQ16Nhonnkn6bkKK6NNViODj8QespZe50DGQhvD0%3D&sp=r&spr=https&sr=b&sv=2019-12-12": x509: certificate is valid for *.githubassets.com, githubassets.com, not pkg-containers.githubusercontent.com
`

**Comment by CaramelFur** [comment]
Hi there, this was an issue with github. Not with this specific project.
