### ISSUE TITLE
Help me log in to my self hosted container

### ISSUE THREAD

**Issue by trijste** [CaramelFur/Picsur#43]
How do I create my own account and log in to it? I thought I would use the credentials in the docker-compose file, or change them. I tried to change aspects of the docker-compose file, but I could no longer reach the service at all. I've deleted the container, but would appreciate a lesson. Thanks!

**Comment by CaramelFur** [comment]
Hi there, the environment variable `PICSUR_ADMIN_PASSWORD` in the docker compose decides the password of the user `admin`. This password is populated only on first start, after this the environment variable is no applicable. If you wish to change the password you will have to do so via the admin dashboard.
If you then want to add more users, you will have to either enable the registration permission on guests. Or manually add new users from the admin dashboard.

**Comment by trijste** [comment]
@CaramelFur Thanks for the response. I will give it another go. It will be just me. Ideally I can use Picur to host content and point to it for personal sites, like a portfolio.

**Comment by CaramelFur** [comment]
@trijste Has the issue been resolved?

**Comment by iAmSaugata** [comment]
Is there any way to change the password forcefully? probably from database? I am currently locked out after recent update and my older password no longer working. All the images I have uploaded will be lost if I create new one from scratch.

**Comment by trijste** [comment]
> @trijste Has the issue been resolved?

I'm sorry I haven't yet attempted to resolve. I will report back after attempting later today.

**Comment by CaramelFur** [comment]
@trijste 
I have not heard back anymore, so I assume this issue has been resolved, if not please let know.

**Comment by trijste** [comment]
> @trijste 
> 
> I have not heard back anymore, so I assume this issue has been resolved, if not please let know.

Sorry for not getting back to you I just haven't picked this back up yet. I will reach out again once I do to say thanks or ask another question.
