### ISSUE TITLE
[Feature request] Add Progressive Web App manifest

### ISSUE THREAD

**Issue by starbuck93** [CaramelFur/Picsur#47]
Just got Picsur up and running in Docker with Cloudflare Tunnels. Super cool so far. I "installed" it on my Android home screen and it's only a bookmark, not a [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable). I think all that's needed would be to add the [manifest.json](https://www.google.com/search?q=pwa+manifest+generator), add some links in the <head> tag and [generate the icon](https://www.google.com/search?q=PWA%20icon%20generator) in various sizes.

**Comment by CaramelFur** [comment]
Thanks for the suggestion

**Comment by CaramelFur** [comment]
Added in commit, will make its way to release eventually.
