### ISSUE TITLE
copy not working in safari

### ISSUE THREAD

**Issue by rolikeusch** [CaramelFur/Picsur#49]
if you click on the copy button within safari nothing is actually copied. this happens with mobile safari on iphone and also in safari on mac.

![](https://img.roli.io/2b4w3NUiAcqVQc2sYDiVfRv2u16FX0rVBobv1btsvY8/rs:fit:1024:1024:1/g:no/bG9jYWw6Ly8vcGlj/c3VyLWNvcHkucG5n.jpg)

**Comment by CaramelFur** [comment]
Has been solved, and will be fixed in next release
