### ISSUE TITLE
Copy to clipboard button throws an error

### ISSUE THREAD

**Issue by crosa7** [CaramelFur/Picsur#54]
In the latest version when clicking on any "copy to clipboard" button, it shows an error in the flash message and does not copy the text to the clipboard. This is more critical when you want to copy an api key, as there is no other way to get this. Thanks in advance

**Comment by CaramelFur** [comment]
Please ensure you are hosting picsur on an HTTPS endpoint. Otherwise the browser does not get access to clipboard functionality.
