### ISSUE TITLE
[Feature Request] Identity Provider Support

### ISSUE THREAD

**Issue by louis-sicko** [CaramelFur/Picsur#59]
I would like to connect my Identity Provider (In my Case Authentik) with Picsur.

Roles could be mapped by OIDC Group Claims for example.

**Comment by chennin** [comment]
I would use LDAP if it was possible

**Comment by paulcsiki** [comment]
OIDC would be fancy, thank you.

**Comment by bmcgonag** [comment]
I too would love to see OIDC options included for Picsur. Love the software by the way!

**Comment by CaramelFur** [comment]
Adding this requires basically rewriting half the program, I unfortunately do not have the time for that, so this will not be added.
If however someone else decides to take on the task, I'm happy to accept new pull requests.
