### ISSUE TITLE
hosted image works in some places, not in others

### ISSUE THREAD

**Issue by mptpro** [CaramelFur/Picsur#64]
I have a vey strange problem.... my hosted images render in some place but not in others. PS, I even tried the Picsur demo with the same behaviour.

Images display properly:
- Chrome browser
- Link preview in Telegram, Facebook, LinkedIn, Threads, 
- image displays correctly in Google sheets using the "image(url)" function
- Link preview in Facebook
- 

Images do not display properly:
- Safari browser
- In markdown and html (I've tried in Joplin, WikiJS, Home Assistant card with image display, and an online markdown renderer. 
- Twitter preview doesn't work.

It's very strange and I can't figure it out.

**Comment by chennin** [comment]
If you open up your browser's dev tools and (re)load a page where the pic does not work, there will probably be an error on the network or console tabs that would say why.  Or if you're willing to share a URL here, anyone here could do that to.

**Comment by chennin** [comment]
Ok - but without more information it's impossible to answer the question for sure.

**Comment by shinji257** [comment]
We can probably use the cat picture on caramelfur.dev.
It gets blocked on Brave and it appears the header has `strict-origin-when-cross-origin` set but it doesn't actually set a policy.
Yes.  To Brave caramelfur.dev and i.caramelfur.dev are different domains.

![image](https://github.com/CaramelFur/Picsur/assets/261005/9701ead5-d4b0-4130-a638-099448fb592a)
![image](https://github.com/CaramelFur/Picsur/assets/261005/dffdf9f8-30b8-4c4d-8588-e5e605d7c56f)

**Comment by CaramelFur** [comment]
Should be fixed in next version
