### ISSUE TITLE
401报错

### ISSUE THREAD

**Issue by yangpin97** [CaramelFur/Picsur#65]
我把 guest 的所有权限删除，然后把保留原文件开启，我退出登录之后，发现就无法在打开登录界面了，直接报错： [https://photo. 我的域名.com/user/login](https://photo.xn--eqrt2gyzlkkv.com/user/login)

https://img.gugu.ovh/i/2023/10/23/n7jtir.webp

401 - Permission Denied
You do not have access to this page

**Comment by Discolor3182** [comment]
I installed this yesterday and it was working fine. Today I am getting the same error.

**Comment by CaramelFur** [comment]
If you are not logged in, you are the guest. If you then remove the permission for guest to log in, you lock yourself out.
While this might seem kinda obvious, I do agree that the fact that this is possible is kinda stupid. I'll see about locking the login permission.

**Comment by ALERTua** [comment]
Ah, so it's just a login option for a guest user. I thought this was an option for a guest user to be able to log in using, like, guest:guest, or something. This is very nice of you to find out about our common issue without any logs :) Hope you come out with a good solution! Thank you for your work!

**Comment by CaramelFur** [comment]
It should now be locked in the next version

**Comment by yangpin97** [comment]
@CaramelFur Looking forward to your release!

**Comment by CaramelFur** [comment]
@yangpin97 new release has already been pushed ^^

**Comment by yangpin97** [comment]
@CaramelFur Can can, test use function is normal, but I believe most users may have these two suggestions, you have time to consider whether it can be realized.
1, web support Chinese
2、Support short links
