### ISSUE TITLE
how to add a prepath

### ISSUE THREAD

**Issue by Guoxweii** [CaramelFur/Picsur#67]
i set traefik path is https://host/picsur to the container, but the asset file without this path

path is 
<img width="1722" alt="image" src="https://github.com/CaramelFur/Picsur/assets/689550/a0c3ae8c-f1e7-48c1-be15-4ea6c72072a5">

console is

<img width="1289" alt="image" src="https://github.com/CaramelFur/Picsur/assets/689550/8d09e04b-06de-4179-a3c8-e5fa92e596ef">

how to reslove this issue

**Comment by CaramelFur** [comment]
Hi there, it is not supported to run picsur on a subpath, you will need to give it its own port or domain name.

**Comment by jovan-cn** [comment]
Hi, not everyone has subdomian, support subpath deploy will be significant  for us.
