### ISSUE TITLE
issues upgrading from alpine-14 to latest

### ISSUE THREAD

**Issue by Scotty1928** [CaramelFur/Picsur#68]
i am using an older docker-compose.yml i got from mariushosting.com. i have only just recently found out you moved your repo to here so i tried updating but have not found a way to do so.

how would i migrate any and all data?

these i am using currently:

image: ghcr.io/rubikscraft/picsur
postgres:14-alpine

**Comment by CaramelFur** [comment]
You should be able to just change the ghcr.io/rubikscraft/picsur to ghcr.io/caramelfur/picsur
And everything should just work
