### ISSUE TITLE
Replace image whilst keeping same URL?

### ISSUE THREAD

**Issue by mptpro** [CaramelFur/Picsur#73]
Is it possible to replace an existing image whilst keeping the same URL?

I have a training wiki (I train financial advisors), and I have a lot of screenshots that I host in my Picsur. Each week I need to update a few of these screenshots with new information. Currently, I need to upload the new screenshots and then update all the URLs on my wiki. It would be great if I could just replace the existing screenshots in Picsur without having to update the URLs on my wiki that point to those screenshots.

thanks

**Comment by CaramelFur** [comment]
Sorry, but this is not something that will be added. The whole idea is that one url only ever means one thing. This makes many other things such as caching much easier.

A way to solve this might be to use a short url generator that allows you to modify the target url later on.
