### ISSUE TITLE
the quality% didn't work

### ISSUE THREAD

**Issue by BenBenJian** [CaramelFur/Picsur#82]
set the quality to 10, it didn't work,
the picture still big.

**Comment by BenBenJian** [comment]
![image](https://github.com/CaramelFur/Picsur/assets/96902190/c9e446f5-7059-4733-b020-bb87bdbabdf7)

**Comment by CaramelFur** [comment]
The quality changes the image quality, not the image size. If you want to change the size, adjust the width and/or height.
