### ISSUE TITLE
Thumbnails are not correct

### ISSUE THREAD

**Issue by aldumil** [CaramelFur/Picsur#84]
The displayed thumbnails for images are not correct and they change everytime the page is refreshed, occasionally all the thumbnails will the same image. The names are correct, and if I open the image page it's fine. Not really sure how to diagnose the issue, no errors anywhere as far as I can tell.

**Comment by cwinl** [comment]
The same to me .  I'm confused for a few seconds. want to konw how to fix it.

**Comment by chrgeorgeson** [comment]
It's a shame I, too, run into this problem.

I like Picsur and have set up some great integrations. I frequently take screenshots on my desktop/laptop/phone and have set up automation to upload all my screenshots to Picsur with a 2-week expiration. However, it's hard to go through them all and find prior screenshots that all look like the same image on the thumbnail.  I might need to find something else but I really don't want to.

**Comment by RayBomb87** [comment]
same here, its really hard to find the correct picture when the pic name is generic and the preview is wrong/changes on every refresh

**Comment by chrgeorgeson** [comment]
> 
> Can I ask you how you set-up the automation to upload a photos in a particular folder to Picsur? Thanks!

Sure! I primarily use Windows on both my desktop and laptop, though a similar approach could be applied on Linux or Mac.I've set up a PowerShell script that monitors a specific folder, and I run this script as a service using NSSM (Non-Sucking Service Manager) to simplify the process.

 For taking screenshots, I use Greenshot, and I configure it to automatically save all files to a designated directory. When a new image is detected in this directory, the PowerShell script uploads it to Picsur via an API call, setting a 2-week expiration for the image.

Additionally, on my Android phone, I use Tasker to monitor my screenshots directory. Whenever a new screenshot is captured, Tasker uploads it to a Google Drive folder. 

These files are then synced to my computer, where another service managed by NSSM performs a similar upload task for my Android screenshots.

This ensures that all my screenshots are automatically backed up to Picsur, regardless of the device I'm using.

I just set it up with ZipLine as an alternative to Picsur but I would prefer to stay with Picsur. I also tried reaching out to the developer via email and so far no response. Tis the way sometimes 🤣

**Comment by chrgeorgeson** [comment]
> Thank you @chrgeorgeson !
> 
> If you have the time, can you explain this step a little, or point me in the right direction?
> 
> > the PowerShell script uploads it to Picsur via an API call, setting a 2-week expiration for the image.

The upload process you're setting up involves two main API calls:

Uploading the image - This initial step uploads the image to the server.
Updating the image - After uploading, you'll need to update the image to set its expiration date.

Here's a basic outline of the API endpoints you'll be working with:

- Upload API Endpoint: https://picsur.yourserver.com/api/image/upload
- Update API Endpoint: https://picsur.yourserver.com/api/image/update

**You will need to manage bearer tokens for authentication.** 

The process involves uploading each image and then capturing the unique ID (UID) of the uploaded image. This UID is crucial as it's required to set the expiration date for the image.

Here’s a quick rundown of how it’s done:

- Loop Through Images: Using a foreach loop, iterate through each image in your designated folder.
- Upload Each Image: For each image, send a POST request to the upload endpoint.
- Capture Image UID: After uploading, extract the UID from the response.
- Set Expiration Date: Send another POST request to the update endpoint, including the image UID and the desired expiration date.

You can find detailed examples of how to handle these requests in your preferred programming language at the following Postman documentation links:

[Upload Image API](https://go.postman.co/caramel-team/workspace/picsur/documentation/1841871-78e559b6-4f39-4092-87c3-92fa29547d03?entity=request-c8a402e1-a134-4829-a9fe-b45d789d9c42)
[Update Image API](https://go.postman.co/caramel-team/workspace/picsur/documentation/1841871-78e559b6-4f39-4092-87c3-92fa29547d03?entity=request-19f43cb7-b987-4993-845d-c775e0190443)

Lastly, while I prefer using Greenshot for its features and flexibility, it’s worth noting that ShareX also integrates **natively** with Picsur and theoretically would simplify and possibly eliminate some of the steps you're manually handling with PowerShell scripts. It could be a worthwhile alternative to consider.

**Comment by cbuck** [comment]
Is this still an issue for everyone? Is there a solution or workaround? I am experiencing this behavior immediately after deployment. I only have four images and only one of two of them are the correct thumbnail. I refresh, and the bad behavior persists but the images are different.

**Comment by chrgeorgeson** [comment]
> Is this still an issue for everyone? Is there a solution or workaround? I am experiencing this behavior immediately after deployment. I only have four images and only one of two of them are the correct thumbnail. I refresh, and the bad behavior persists but the images are different.

Yes this is still a problem with zero workarounds as far as I know.

I had to leave picsur behind and switch to ZipLine.

**Comment by RayBomb87** [comment]
Yeah, still got the issue.

**Comment by CaramelFur** [comment]
I have rewritten the part that renders the thumbnails, this should now have fixed the bug. Please give the new 0.5.5 a try, and see if it also solves it for you guys.

**Comment by aldumil** [comment]
> I have rewritten the part that renders the thumbnails, this should now have fixed the bug. Please give the new 0.5.5 a try, and see if it also solves it for you guys.

Thanks @CaramelFur! I just tested 0.5.5 and I think it is still doing the same thing. Multiple images will load with the same thumbnail and every page refresh the thumbnail for everything will change. I appreciate everything! If I can provide anything useful please let me know!

I did also get a "this version of the server is not compatible with the client" message the first time I loaded after upgrading. Only got it the one time though.

I did try to delete the database and set it up again, just in case, but the issue persists.

**Comment by CaramelFur** [comment]
@aldumil Damn, that sucks. But if you could give me your exact system, os and browser setup with the images you used, that would be helpful. Cause I have only seen the bug happen once ever on my system, so that makes it awfully hard to track down.

**Comment by aldumil** [comment]
> @aldumil Damn, that sucks. But if you could give me your exact system, os and browser setup with the images you used, that would be helpful. Cause I have only seen the bug happen once ever on my system, so that makes it awfully hard to track down.

Sure! You can view my Picsur instance [here ](https://picsur.mumquhar.com)in case that is helpful at all. I could give you login as well so you can see the issue yourself....don't know if that would be helpful or not.

It is hosted on an Unraid machine. As far as viewing, I hadn't tested this until your comment, but it seem like Safari on iOS seems to not have the issue, neither does Firefox on Windows 11. Chrome on both of those does have the wrong thumbnail issue though. Far from conclusive testing, my instance has like 10 images and I just clicked around and refreshed for awhile, but it isn't an intermittent issue when it does happen, it's either all of them are completely wrong, or works without issue.

Let me know if I can be of any help!

**Comment by CaramelFur** [comment]
Thank you. But I think I already found the cause of the bug, TLDR: do not use unix time MS as a unique ID 🤦🏼

**Comment by CaramelFur** [comment]
@aldumil I pushed a new 0.5.6 tag to docker, could you try that and see if the issue persists?

**Comment by aldumil** [comment]
> @aldumil I pushed a new 0.5.6 tag to docker, could you try that and see if the issue persists?

That looks like it is fixed! 

I didn't see anywhere to tip you or anything. If that's not your thing, then know you have my gratitude, but if it is, please share so I can thank you properly!

**Comment by CaramelFur** [comment]
Fantastic, I'll make a proper release announcement then, and close the corresponding issues.
And if you wanted to send me a tip, there should be sponsor button on the main github repo page.

**Comment by RayBomb87** [comment]
Just tested myself 0.5.6 and the issue is gone. Halleluja!

**Comment by RayBomb87** [comment]
I also got the warning..

**Comment by cbuck** [comment]
The loud sound emanating from Tennessee was me tripping over the dog to deploy the new build. 0.5.6 fixed the issue for me! Thanks a ton @CaramelFur !!!
