### ISSUE TITLE
Running on unRAID - Message states: the server is not compatible with this version of the client.

### ISSUE THREAD

**Issue by Tyree** [CaramelFur/Picsur#86]
I just loaded up the web interface for my unRAID Picsur container and I see the message:
Server is not compatible
The server is not compatible with this version of the client. You can ignore this, but expect things not to work.

Is there something I can do to fix this? It's all in one container, what can I be running that is incomptaible?

Thanks!

**Comment by CaramelFur** [comment]
It seems this check is kinda broken, I've disabled it in the latest version, and will work on one that doesn't behave oddly.
