### ISSUE TITLE
Grouping images in folders?

### ISSUE THREAD

**Issue by jaschuu** [CaramelFur/Picsur#90]
not really an issue more of a feature request,

would be nice to be able to group images in folders.

**Comment by prohand** [comment]
Yes, it's great feature

**Comment by CaramelFur** [comment]
This feature request is already there as "Albums", so I'll close this issue

**Comment by prohand** [comment]
Hello, this feature does not exist in release 0.5.6
Do you know when this feature will be released?

Thanks
