### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by mcmasterp** [CaramelFur/Picsur#93]
Great work so far just trying to plan ahead. will there be anymore development on this great project. it works well as is except for the strange thumbnails all screwed up issue.

Hoping it is still alive!

**Comment by CaramelFur** [comment]
I am trying to keep it alive as long as I can, so right now not dead.
But I only have so much time sadly, so actually creating new features is gonna be a hard one.

**Comment by mcmasterp** [comment]
Yeah I totally get that and no worries it's just so close to working well. The thumbnails are the biggest and so far only issue I see

**Comment by CaramelFur** [comment]
I've been taking a look at that a little too, but I can't for the life of me reproduce the bug.
Maybe the newer angular version fixed it?
Could you see if with the new Picsur version it still happens, and if it does, could you pass a collection of images that triggers the bug?

**Comment by mcmasterp** [comment]
I had deleted the image on my unraid server but I just reinstalled it and got it back up and still the same behavior. Mine is exposed to the internet s you are welcome to login and see for yourself. PM me I already have a U&P setup for you

**Comment by CaramelFur** [comment]
Yeah that would be nice, also maybe switching to a chat app instead of github might be better?
