### ISSUE TITLE
Questions - Logs and Fail2ban

### ISSUE THREAD

**Issue by 60plus** [CaramelFur/Picsur#99]
Hello, can someone tell me where I can find log file?

And does anyone know how to write a regex for Fail2ban? 

Thank you for help.

**Comment by CaramelFur** [comment]
You can get the logs by calling `docker logs picsur`.
For fail2ban I have no clue, sorry.

**Comment by 60plus** [comment]
Is it possible to save logs to a file ?
This would help to set up protection by fail2ban and other similar.

**Comment by CaramelFur** [comment]
You can configure docker compose to send the logs to file, more info can be found here: https://docs.docker.com/engine/logging/configure/#supported-logging-drivers
